name: CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25
          cache-dependency-path: builder/go.sum
      - uses: actions/checkout@v5
      - run: cd builder && go test -race ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25
          cache-dependency-path: builder/go.sum

      - uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Checkout base branch
        if: ${{ github.ref != 'refs/heads/photos' }}
        uses: actions/checkout@v5
      - name: Checkout main branch
        if: ${{ github.ref == 'refs/heads/photos' }}
        uses: actions/checkout@v5
        with:
          ref: main
      - name: Checkout photos branch
        uses: actions/checkout@v5
        with:
          ref: photos
          path: pages/photos

      - name: Cache assets
        uses: actions/cache@v4
        with:
          path: .vercel/cache
          key: build-cache-${{ hashFiles('pages/photos/**/*.jpg') }}
          restore-keys: |
            build-cache-${{ hashFiles('pages/photos/**/*.jpg') }}
            build-cache-

      - name: Install dependencies
        run: npm ci
        working-directory: functions/log.func

      - name: Build pages
        run: make build

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: .vercel/output/
          include-hidden-files: true

  lighthouse:
    name: Lighthouse Test
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref != 'refs/heads/photos' }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Load artifact
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: .vercel/output/

      - uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: .github/lighthouse.json
          runs: 3
          urls: |
            /
            /blog
            /blog/2020/05/blanktar-renewal
            /blog/2023/08/golang-goldmark-custom-renderer
            /works
            /photos
          uploadArtifacts: true

  preview:
    name: Preview Deploy
    runs-on: ubuntu-latest
    needs: [test, build]
    if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/photos' }}
    permissions:
      contents: read
      deployments: write
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Instal Vercel CLI
        run: npm install --global vercel@latest

      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Load artifact
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: .vercel/output/

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        id: deploy
        run: |
          echo -n "url=" >> $GITHUB_OUTPUT
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} >> $GITHUB_OUTPUT

  production:
    name: Production Deploy
    runs-on: ubuntu-latest
    needs: [test, lighthouse, build]
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/photos' }}
    permissions:
      contents: read
      deployments: write
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Instal Vercel CLI
        run: npm install --global vercel@latest

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
      - name: Load artifact
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: .vercel/output/

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        id: deploy
        run: |
          echo -n "url=" >> $GITHUB_OUTPUT
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod >> $GITHUB_OUTPUT
